config/routes.rb
InterventionTracker::Application.routes.draw do
  resources :interventions

  resources :practitioners

end

app/models/intervention.rb
class Intervention < ActiveRecord::Base
  attr_accessible :cost, :grouping, :name
end

app/models/practitioner.rb
class Practitioner < ActiveRecord::Base
  attr_accessible :name, :specialty
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  # GET /interventions
  # GET /interventions.json
  def index
    @interventions = Intervention.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interventions }
    end
  end

  # GET /interventions/1
  # GET /interventions/1.json
  def show
    @intervention = Intervention.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @intervention }
    end
  end

  # GET /interventions/new
  # GET /interventions/new.json
  def new
    @intervention = Intervention.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @intervention }
    end
  end

  # GET /interventions/1/edit
  def edit
    @intervention = Intervention.find(params[:id])
  end

  # POST /interventions
  # POST /interventions.json
  def create
    @intervention = Intervention.new(params[:intervention])

    respond_to do |format|
      if @intervention.save
        format.html { redirect_to @intervention, notice: 'Intervention was successfully created.' }
        format.json { render json: @intervention, status: :created, location: @intervention }
      else
        format.html { render action: "new" }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interventions/1
  # PUT /interventions/1.json
  def update
    @intervention = Intervention.find(params[:id])

    respond_to do |format|
      if @intervention.update_attributes(params[:intervention])
        format.html { redirect_to @intervention, notice: 'Intervention was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1
  # DELETE /interventions/1.json
  def destroy
    @intervention = Intervention.find(params[:id])
    @intervention.destroy

    respond_to do |format|
      format.html { redirect_to interventions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/practitioners_controller.rb
class PractitionersController < ApplicationController
  # GET /practitioners
  # GET /practitioners.json
  def index
    @practitioners = Practitioner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @practitioners }
    end
  end

  # GET /practitioners/1
  # GET /practitioners/1.json
  def show
    @practitioner = Practitioner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @practitioner }
    end
  end

  # GET /practitioners/new
  # GET /practitioners/new.json
  def new
    @practitioner = Practitioner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @practitioner }
    end
  end

  # GET /practitioners/1/edit
  def edit
    @practitioner = Practitioner.find(params[:id])
  end

  # POST /practitioners
  # POST /practitioners.json
  def create
    @practitioner = Practitioner.new(params[:practitioner])

    respond_to do |format|
      if @practitioner.save
        format.html { redirect_to @practitioner, notice: 'Practitioner was successfully created.' }
        format.json { render json: @practitioner, status: :created, location: @practitioner }
      else
        format.html { render action: "new" }
        format.json { render json: @practitioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /practitioners/1
  # PUT /practitioners/1.json
  def update
    @practitioner = Practitioner.find(params[:id])

    respond_to do |format|
      if @practitioner.update_attributes(params[:practitioner])
        format.html { redirect_to @practitioner, notice: 'Practitioner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @practitioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practitioners/1
  # DELETE /practitioners/1.json
  def destroy
    @practitioner = Practitioner.find(params[:id])
    @practitioner.destroy

    respond_to do |format|
      format.html { redirect_to practitioners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/helpers/practitioners_helper.rb
module PractitionersHelper
end

app/views/interventions/_form.html.erb
<%= form_for @intervention, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :grouping, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :grouping, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cost, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                interventions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/interventions/edit.html.erb
<%- model_class = Intervention -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/interventions/index.html.erb
<%- model_class = Intervention -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:grouping) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:cost) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= link_to intervention.id, intervention_path(intervention) %></td>
        <td><%= intervention.grouping %></td>
        <td><%= intervention.name %></td>
        <td><%= intervention.cost %></td>
        <td><%=l intervention.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_intervention_path(intervention), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      intervention_path(intervention),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_intervention_path,
            :class => 'btn btn-primary' %>

app/views/interventions/new.html.erb
<%- model_class = Intervention -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/interventions/show.html.erb
<%- model_class = Intervention -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:grouping) %>:</strong></dt>
  <dd><%= @intervention.grouping %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @intervention.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cost) %>:</strong></dt>
  <dd><%= @intervention.cost %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              interventions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_intervention_path(@intervention), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              intervention_path(@intervention),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MHP Intervention Tracker</title>
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Mental Health Pharmacy Intervention Tracker</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Browse Practitioners", practitioners_path %></li>
          <li><%= link_to "Browse Intervention Types", interventions_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
  	<div class="span9"><%= yield %></div>
  	<div class="span3">
  		<h2>About us</h2>
  		<p>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
  	</div>
  </div>
</div>

</body>
</html>

app/views/practitioners/_form.html.erb
<%= form_for @practitioner, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :specialty, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :specialty, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                practitioners_path, :class => 'btn' %>
  </div>
<% end %>

app/views/practitioners/edit.html.erb
<%- model_class = Practitioner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/practitioners/index.html.erb
<%- model_class = Practitioner -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:specialty) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @practitioners.each do |practitioner| %>
      <tr>
        <td><%= link_to practitioner.id, practitioner_path(practitioner) %></td>
        <td><%= practitioner.specialty %></td>
        <td><%= practitioner.name %></td>
        <td><%=l practitioner.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_practitioner_path(practitioner), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      practitioner_path(practitioner),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_practitioner_path,
            :class => 'btn btn-primary' %>

app/views/practitioners/new.html.erb
<%- model_class = Practitioner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/practitioners/show.html.erb
<%- model_class = Practitioner -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:specialty) %>:</strong></dt>
  <dd><%= @practitioner.specialty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @practitioner.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              practitioners_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_practitioner_path(@practitioner), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              practitioner_path(@practitioner),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>